# Generated by Django 4.1.3 on 2022-12-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=100, verbose_name='Domain Name')),
                ('reached_at', models.DateTimeField(auto_now=True, verbose_name='Reached at')),
                ('status', models.CharField(default='Running', max_length=30, verbose_name='Status')),
                ('contact_page', models.CharField(default='', max_length=150, verbose_name='Contact Page')),
                ('contact_form', models.BooleanField(default=False, verbose_name='Contact Form')),
                ('form_sent', models.BooleanField(default=False, verbose_name='Form Sent')),
                ('went_over_manually', models.BooleanField(default=False, verbose_name='Went Over Manually')),
                ('sent_manually', models.BooleanField(default=False, verbose_name='Sent Manually')),
                ('emails_found', models.IntegerField(blank=True, default=0, verbose_name='Emails Found')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30, verbose_name='Name')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('phone_number', models.IntegerField(blank=True, default=0, verbose_name='Phone Number')),
                ('company', models.CharField(max_length=50, verbose_name='Company')),
                ('department', models.CharField(max_length=50, verbose_name='Department')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
            ],
        ),
    ]
