# Generated by Django 4.1.3 on 2023-01-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_domain_contact_form_alter_domain_contact_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='In progress', max_length=30, verbose_name='Status'),
        ),
    ]
