# Generated by Django 4.1.3 on 2023-01-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_finishe_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='finishe_date',
            new_name='finished_date',
        ),
    ]
