# Generated by Django 4.1.3 on 2023-02-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_finishe_date_task_finished_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_name', models.CharField(max_length=30, verbose_name='Name')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('phone_number', models.IntegerField(blank=True, default=0, verbose_name='Phone Number')),
                ('company', models.CharField(max_length=50, verbose_name='Company')),
                ('department', models.CharField(max_length=50, verbose_name='Department')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
            ],
        ),
    ]
