# Generated by Django 4.1.3 on 2023-02-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_preset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='preset_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Name'),
        ),
    ]
