# Generated by Django 4.1.3 on 2023-02-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_preset_preset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='preset_name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
    ]
